apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-alpine
  name: weather-alpine
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weather-alpine
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: weather-alpine
  name: weather-alpine
spec:
  containers:
  - image: chrisley75/weather-alpine:0.4
    name: weather-alpine
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
