apiVersion: v1
kind: Service
metadata:
  name: weather-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: weather-alpine 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
