apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: image
  newName: quay.io/chrisley7506/simple-nextjs-app
  newTag: latest
commonLabels:
  app: nextjs-app
  app.kubernetes.io/instance: nextjs-app-chrisley
  app.kubernetes.io/name: nextjs-app-chrisley
replicas:
- name: nextjs-app
  count: 1
